---
title: "Lab 7 Assignment: Group 29"
format:
  html:
    embed-resources: true
editor: visual
---

## Load libraries

```{r}
library(tidyverse)
library(broom)
library(cowplot)
```

## Load data

```{r}

raw_dir <- "data/_raw/"
data_file <- "gravier.RData"
data_loc <- "https://github.com/ramhiser/datamicroarray/raw/master/data/"

if( !dir.exists(raw_dir) ){
  dir.create(path = raw_dir)
}
if( !file.exists(str_c(raw_dir, data_file)) ){
  download.file(
    url = str_c(data_loc, data_file),
    destfile = str_c(raw_dir, data_file))
}
load(file = str_c(raw_dir, data_file))

```

The data frame is then converted to a tibble and early_metastasis is added as a column in the beginning.

```{r}

gravier <- gravier |>
  bind_cols() |>
  as_tibble() |>
  mutate(y = case_when(y == "poor" ~ "poor",
                       y == "good" ~ "good")) |> 
  relocate(early_metastasis = y) |>
  select(1:101)
```

```{r}
pca_fit <- gravier %>% 
  select(where(is.numeric)) %>% # retain only numeric columns
  prcomp(scale = TRUE) # do PCA on scaled data
```

```{r}
pca_fit |> 
  augment(gravier) |> 
  ggplot(aes(.fittedPC1, .fittedPC2, color = early_metastasis)) +
  geom_point(size = 1.5, alpha = 0.4) +
  scale_color_manual(values = c(poor = "red", good = "blue")) +
  labs(
    title = "PCA of Gravier data",
    color = "early metastasis"
  ) +
  theme_minimal()

```
